### ISSUE TITLE
serve打包部署到服务器，日志管理中调用统计报错

### ISSUE THREAD

**Issue by shunfengzero** [tianmiantech/WeFe#13]
![image](https://user-images.githubusercontent.com/31364213/139417178-0a7f2348-612d-4c5b-80bd-00f83e0b151b.png)

**Comment by shunfengzero** [comment]
mysql中sql_Mode=only_full_group_by导致的问题，已修复mysql忽略这个问题。还是建议代码中去修复这个问题。

**Comment by zlzhao998** [comment]
好的，后续版本安排修复此bug
